displayName=True Tile Corner Marker
author=jmichaelscott93-blip
description=Dynamically marks the four corner tiles two tiles diagonally from your true tile
tags=tile,marker,overlay
plugins=com.jeffplugins.truetilecornermarker.TrueTileCornerMarkerPlugin
version=
build=standard
